language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

branches:
  only:
    - master

notifications:
  email:
    - github@steve-lenz.de

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
